config/routes.rb
Rails.application.routes.draw do

  resources :opravas

  resources :organizators

  resources :riesitel_seria do
    collection do
      get :riesitelia_serie
      post :edit_riesitels
    end
  end

  resources :riesitels do
    collection do
      post :add_riesitels
      post :add_riesitels_to_seria
    end
  end

  resources :homepages do
    collection do
      get :login
      post :login
    end
  end

  root "homepages#login"

  resources :komentars

  resources :priklads do
    member do
      get :edit_priklad
      patch :edit_priklad
    end
  end

  resources :kolos do
    member do
      post :add_priklads
      delete :remove_priklad
    end
  end

  resources :knizkas do
    member do
      post :add_obsah
      delete :remove_obsah
      get :zadania
      get :zadania_edit
      post :zadania_edit
      patch :zadania_edit
      get :vzoraky
      get :vysledkovka
      get :clanok
      post :gen_pdf
    end
  end

  resources :seria do
    resources :knizkas
  end

  resources :rocniks

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/knizka.rb
class Knizka < ActiveRecord::Base
  has_many :knizka_obsahs, dependent: :destroy
  has_many :pdfs, dependent: :destroy
end

app/models/knizka_obsah.rb
class KnizkaObsah < ActiveRecord::Base
  belongs_to :knizka
end

app/models/kolo.rb
class Kolo < ActiveRecord::Base
  has_many :priklads
end

app/models/komentar.rb
class Komentar < ActiveRecord::Base
  belongs_to :priklad
end

app/models/oprava.rb
class Oprava < ActiveRecord::Base
end

app/models/organizator.rb
class Organizator < ActiveRecord::Base
end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  belongs_to :knizka
end

app/models/priklad.rb
class Priklad < ActiveRecord::Base
  has_many :komentars, dependent: :destroy
  belongs_to :kolo
end

app/models/riesitel.rb
class Riesitel < ActiveRecord::Base
  has_many :riesitel_seria
end

app/models/riesitel_serium.rb
class RiesitelSerium < ActiveRecord::Base
  belongs_to :riesitel
  belongs_to :serium
end

app/models/rocnik.rb
class Rocnik < ActiveRecord::Base
  after_save :create_serie_kola

  def name
    "#{cislo}. ročník"
  end

  def create_serie_kola
    z = Serium.create(nazov: 'Zimná', rocnik: cislo)
    l = Serium.create(nazov: 'Letná', rocnik: cislo)
    (1..3).each do |c|
      Kolo.create(cislo: c, seria: 'Zimná', rocnik: cislo)
      Kolo.create(cislo: c, seria: 'Letná', rocnik: cislo)
    end
  end
end

app/models/serium.rb
class Serium < ActiveRecord::Base
  has_many :riesitel_seria
end

app/controllers/knizkas_controller.rb
class KnizkasController < ApplicationController
  before_action :set_knizka, only: [:show, :edit, :update, :destroy, :add_obsah, :remove_obsah, :zadania, :zadania_edit, :vzoraky, :vysledkovka, :clanok, :gen_pdf]


  def zadania
    @obsah = KnizkaObsah.find(params[:format])
    @c_kolo = @obsah.nazov.split('Zadania ')[1].split('. kola')[0]
    @kolo = Kolo.where(rocnik: @knizka.rocnik, seria: @knizka.seria, cislo: @c_kolo).take
    @priklady = @kolo.priklads.order(:cislo_v_kole)
  end

  def zadania_edit
    @obsah = KnizkaObsah.find(params[:format])
    @c_kolo = @obsah.nazov.split('Zadania ')[1].split('. kola')[0]
    @kolo = Kolo.where(rocnik: @knizka.rocnik, seria: @knizka.seria, cislo: @c_kolo).take
    @priklady = @kolo.priklads.order(:cislo_v_kole)

    unless params[:commit].blank?
      @priklady.each do |pr|
        unless params["pred_t_#{pr.cislo_v_kole}"].blank?
          pr.pred_t = params["pred_t_#{pr.cislo_v_kole}"]
        end
        unless params["text_#{pr.cislo_v_kole}"].blank?
          pr.text = params["text_#{pr.cislo_v_kole}"]
        end
        unless params["po_t_#{pr.cislo_v_kole}"].blank?
          pr.po_t = params["po_t_#{pr.cislo_v_kole}"]
        end
        pr.save
      end
      redirect_to zadania_knizka_path(@knizka, @obsah.id), notice: 'zadania_edit'
    end
  end

  def vzoraky

  end

  def vysledkovka

  end

  def clanok

  end

  # GET /knizkas
  # GET /knizkas.json
  def index
    @knizkas = Knizka.all
  end

  # GET /knizkas/1
  # GET /knizkas/1.json
  def show
    @pridany_obsah = @knizka.knizka_obsahs
    @obsah = []
    (1..3).each do |i|
      @obsah << { id: "z#{i}", name: "Zadania #{i}. kola", link: nil } if @pridany_obsah.where(nazov: "Zadania #{i}. kola").count == 0
      @obsah << { id: "vz#{i}", name: "Vzoráky #{i}. kola", link: nil } if @pridany_obsah.where(nazov: "Vzoráky #{i}. kola").count == 0
      @obsah << { id: "vy#{i}", name: "Výsledkovka #{i}. kola", link: nil } if @pridany_obsah.where(nazov: "Výsledkovka #{i}. kola").count == 0
    end
  end

  def add_obsah
    if !params[:obsah].blank?
      params[:obsah].each do |obsah|
        max = @knizka.knizka_obsahs.order('cislo DESC').first
        if max
          max = max.cislo
        else
          max = 0
        end
        if obsah.starts_with?('z')
          cislo = obsah.split('z')[1]
          @knizka.knizka_obsahs.create(nazov: "Zadania #{cislo}. kola", cislo: (max + 1))
        elsif obsah.starts_with?('vz')
          cislo = obsah.split('vz')[1]
          @knizka.knizka_obsahs.create(nazov: "Vzoráky #{cislo}. kola", cislo: (max + 1))
        elsif obsah.starts_with?('vy')
          cislo = obsah.split('vy')[1]
          @knizka.knizka_obsahs.create(nazov: "Výsledkovka #{cislo}. kola", cislo: (max + 1))
        end
      end
    end
    if !params[:clanok_cnt].blank?
      params[:clanok_cnt].to_i.times do |i|
        max = @knizka.knizka_obsahs.order('cislo DESC').first
        if max
          max = max.cislo
        else
          max = 0
        end
        @knizka.knizka_obsahs.create(nazov: 'Článok', cislo: (max + 1))
      end
    end
    if !params[:obsah].blank? || (!params[:clanok_cnt].blank? && params[:clanok_cnt].to_i != 0)
      redirect_to :back, notice: 'ok'
    else
      redirect_to :back, notice: 'nothing_added'
    end
  end

  def remove_obsah
    unless params[:format].blank?
      k = KnizkaObsah.find(params[:format])
      por = k.cislo
      @knizka.knizka_obsahs.where('`cislo` > ?', por).each do |kkk|
        kkk.update(cislo: kkk.cislo - 1)
      end
      k.destroy

      redirect_to :back, notice: 'removed'
    end
  end

  def gen_pdf
    @knizka.pdfs.create
    redirect_to :back, notice: 'pdf_ok'
  end

  # GET /knizkas/new
  def new
    @seria = Serium.find(params[:serium_id])
    @rocnik = Rocnik.find_by_cislo(@seria.rocnik)
    max = Knizka.where(rocnik: @rocnik.cislo, seria: @seria.nazov).order('cislo DESC').first
    if !max
      max = -1
    else
      max = max.cislo
    end
    Knizka.create(cislo: max + 1, rocnik: @rocnik.cislo, seria: @seria.nazov)
    redirect_to :back, notice: 'knizka_added'
  end

  # GET /knizkas/1/edit
  def edit
  end

  # POST /knizkas
  # POST /knizkas.json
  def create
    @knizka = Knizka.new(knizka_params)

    respond_to do |format|
      if @knizka.save
        format.html { redirect_to @knizka, notice: 'Knizka was successfully created.' }
        format.json { render :show, status: :created, location: @knizka }
      else
        format.html { render :new }
        format.json { render json: @knizka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knizkas/1
  # PATCH/PUT /knizkas/1.json
  def update
    respond_to do |format|
      if @knizka.update(knizka_params)
        format.html { redirect_to @knizka, notice: 'Knizka was successfully updated.' }
        format.json { render :show, status: :ok, location: @knizka }
      else
        format.html { render :edit }
        format.json { render json: @knizka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knizkas/1
  # DELETE /knizkas/1.json
  def destroy
    rocnik = Rocnik.where(cislo: @knizka.rocnik).first
    @knizka.destroy
    redirect_to url_for(:controller => 'rocniks', :action => 'show', id: rocnik.id), notice: 'knizka_deleted'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_knizka
    @knizka = Knizka.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def knizka_params
    params.fetch(:knizka, {})
  end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/knizkas_helper.rb
module KnizkasHelper
end

app/helpers/kolos_helper.rb
module KolosHelper
end

app/helpers/komentars_helper.rb
module KomentarsHelper
end

app/helpers/opravas_helper.rb
module OpravasHelper
end

app/helpers/priklads_helper.rb
module PrikladsHelper
end

app/helpers/riesitels_helper.rb
module RiesitelsHelper
end

app/helpers/rocniks_helper.rb
module RocniksHelper
end

app/helpers/seria_helper.rb
module SeriaHelper
end

app/views/knizkas/_form.html.erb
<%= form_for(@knizka) do |f| %>
  <% if @knizka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@knizka.errors.count, "error") %> prohibited this knizka from being saved:</h2>

      <ul>
      <% @knizka.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/knizkas/edit.html.erb
<h1>Editing Knizka</h1>

<%= render 'form' %>

<%= link_to 'Show', @knizka %> |
<%= link_to 'Back', knizkas_path %>

app/views/knizkas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Knizkas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @knizkas.each do |knizka| %>
      <tr>
        <td><%= link_to 'Show', knizka %></td>
        <td><%= link_to 'Edit', edit_knizka_path(knizka) %></td>
        <td><%= link_to 'Destroy', knizka, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Knizka', new_knizka_path %>

app/views/knizkas/new.html.erb
<h1>New Knizka</h1>

<%= render 'form' %>

<%= link_to 'Back', knizkas_path %>

app/views/knizkas/show.html.erb
<div class="ui fluid segment">
  <div class="ui breadcrumb">
    <%= link_to "Home", homepages_path, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <%= link_to "#{@knizka.rocnik}. ročník", rocnik_path(Rocnik.find_by_cislo(@knizka.rocnik)), class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="section"><%= @knizka.seria %> séria</div>
    <i class="right chevron icon divider"></i>
    <div class="active section"><%= @knizka.cislo %>. knižka</div>
  </div>
</div>

<% if notice == 'ok' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Obsah bol úspešne pridaný do knižky.
        </div>
        <p>Skontroluj svoje zmeny.</p>
      </div>
    </div>
<% elsif notice == 'nothing_added' %>
    <div class="ui red icon message">
      <i class="meh mark icon"></i>
      <div class="content">
        <div class="header">
          Nepodarilo sa pridať obsah do tejto knižky.
        </div>
        <p>Nevybral si, čo sa má pridať.</p>
      </div>
    </div>
<% elsif notice == 'removed' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Obsah bol z knižky úspešne odobraný.
        </div>
        <p>Skontroluj svoje zmeny.</p>
      </div>
    </div>
<% elsif notice == 'pdf_ok' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          PDF bolo úspešne vytvorené.
        </div>
        <p>Teraz si ho môžeš prezerať.</p>
      </div>
    </div>
<% end %>

<h1><%= @knizka.cislo %>. knižka</h1>
<h2>Obsah knižky</h2>

<div class="ui two column grid">
  <div class="column">
    <h3>Vybraný obsah</h3>
    <table class="ui teal selectable celled striped very compact small table">
      <thead>
      <tr>
        <th class="one wide"></th>
        <th class="one wide">Por.</th>
        <th class="eight wide">Názov</th>
        <th class="six wide">Akcie</th>
      </tr>
      </thead>

      <tbody>
      <% if @knizka.knizka_obsahs.any? %>
          <% @knizka.knizka_obsahs.order(:cislo).each do |k| %>
              <tr>
                <td>
                  <% if k.cislo != 1 %>
                      <i class="caret up link icon move_up" id="up<%= k.cislo %>"></i>
                  <% end %>
                  <% if k.cislo != @knizka.knizka_obsahs.count %>
                      <i class="caret down link icon move_down" id="down<%= k.cislo %>"></i>
                  <% end %>
                </td>
                <td><%= k.cislo %>.</td>
                <td id="prikladN<%= k.cislo %>"><%= k.nazov %></td>
                <td id="prikladA<%= k.cislo %>">
                  <div class="ui basic buttons">
                    <% if k.nazov.start_with?('Zadania') %>
                        <%= link_to zadania_knizka_path(@knizka, k.id), class: 'ui button' do %>
                            <i class="blue unhide link icon"></i>
                        <% end %>
                    <% elsif k.nazov.start_with?('Vzoráky') %>
                        <%= link_to nil, class: 'ui button', data: { confirm: 'Not implemented.' } do %>
                            <i class="blue unhide link icon"></i>
                        <% end %>
                    <% elsif k.nazov.start_with?('Výsledkovka') %>
                        <%= link_to nil, class: 'ui button', data: { confirm: 'Not implemented.' } do %>
                            <i class="blue unhide link icon"></i>
                        <% end %>
                    <% elsif k.nazov.start_with?('Článok') %>
                        <%= link_to nil, class: 'ui button', data: { confirm: 'Not implemented.' } do %>
                            <i class="blue unhide link icon"></i>
                        <% end %>
                    <% end %>
                    <% if k.nazov.start_with?('Zadania') %>
                        <%= link_to zadania_edit_knizka_path(@knizka, k.id), class: 'ui button' do %>
                            <i class="yellow edit link icon"></i>
                        <% end %>
                    <% elsif k.nazov.start_with?('Článok') %>
                        <%= link_to nil, class: 'ui button', data: { confirm: 'Not implemented.' } do %>
                            <i class="yellow edit link icon"></i>
                        <% end %>
                    <% end %>
                    <%= link_to remove_obsah_knizka_path(@knizka, k.id), class: 'ui button', method: :delete, data: { confirm: 'Naozaj chceš vymazať túto časť knižky?' } do %>
                        <i class="red remove link icon"></i>
                    <% end %>
                  </div>
                </td>
              </tr>
          <% end %>
      <% else %>
          <tr>
            <td colspan="4">Neexistuje žiaden záznam.</td>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="column">
    <h3>Výber obsahu</h3>
    <%= form_tag url_for(:controller => 'knizkas', :action => 'add_obsah'), class: 'ui form' do %>
        <table class="ui teal selectable celled striped very compact small table">
          <thead>
          <tr>
            <th class="two wide" colspan="2">Výber</th>
            <th class="fourteen wide">Názov</th>
          </tr>
          </thead>

          <tbody id="clanok-container">
          <% @obsah.each do |o| %>
              <tr>
                <td colspan="2"><%= check_box_tag "obsah[]", o[:id] %></td>
                <td><%= o[:name] %></td>
              </tr>
          <% end %>
          <tr>
            <td><i class="green plus circle link icon" id="add-clanok"></i></td>
            <td><i class="red minus circle link icon" id="remove-clanok"></i>
            </td>
            <td>Články
              <span class="ui small blue circular label" id="pocet-clankov">0</span>
            </td>
            <%= hidden_field_tag :clanok_cnt, 0 %>
          </tr>
          </tbody>
        </table>
        <%= submit_tag "Pridať obsah", class: 'ui green button' %>
    <% end %>
  </div>
</div>

<h2>PDF</h2>

<div class="ui segment">
  <div class="ui two column grid">
    <div class="four wide column">
      <h3>Vytvorené PDF</h3>
      <table class="ui teal selectable celled striped fluid table">
        <thead>
        <tr>
          <th>Verzia</th>
          <th class="one wide"></th>
        </tr>
        </thead>

        <tbody>
        <% if @knizka.pdfs.any? %>
            <% @knizka.pdfs.order('created_at DESC').each do |pdf| %>
                <tr>
                  <td><%= datetime_format pdf.created_at %></td>
                  <td>
                    <i class="blue unhide link icon refresh"></i>
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr>
              <td colspan="2">Neexistuje žiaden záznam.</td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div class="ui segment">
        <h3>Tvorba PDF</h3>
        <%= form_tag url_for(:controller => 'knizkas', :action => 'gen_pdf'), class: 'ui form' do %>
            <%= check_box_tag :print %> Na tlač<br>
            <%= check_box_tag :logs %> Zachovať zdrojové súbory<br>
            <%= check_box_tag :errors %> Tolerancia chýb<br>
            <%= submit_tag "Vytvor PDF", class: 'ui green button' %>
        <% end %>
      </div>
    </div>
    <div class="twelve wide column">
      <h3>PDF Viewer</h3>
      <% if @knizka.pdfs.count > 0 %>
          <div class="ui embed" style="min-height: 800px;" id="refreshed">
            <embed src="<%= asset_path "pdfs/knizka#{Random.rand(4) + 1230}.pdf" %>"/>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/knizkas/zadania.html.erb
<div class="ui fluid segment">
  <div class="ui breadcrumb">
    <%= link_to "Home", homepages_path, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <%= link_to "#{@knizka.rocnik}. ročník", rocnik_path(Rocnik.find_by_cislo(@knizka.rocnik)), class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="section"><%= @knizka.seria %> séria</div>
    <i class="right chevron icon divider"></i>
    <%= link_to "#{@knizka.cislo}. knižka", @knizka, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="active section">Zadania</div>
  </div>
</div>

<% if notice == 'priklad_edited' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Zadania boli úspešne upravené
        </div>
        <p>Skontroluj svoje zmeny.</p>
      </div>
    </div>
<% elsif notice == 'zadania_edit' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Zadania boli úspešne upravené.
        </div>
        <p>Skontroluj svoje zmeny.</p>
      </div>
    </div>
<% end %>


<div class="ui grid">
  <div class="fourteen wide column"><h1>Zadania <%= @c_kolo %>. kola</h1></div>
  <div class="column">
    <h1>
      <%= link_to zadania_edit_knizka_path(@knizka, @obsah.id) do %>
          <i class="ui large right aligned yellow edit link icon"></i>
      <% end %>
    </h1>
  </div>
</div>

<% if @priklady.any? %>
    <table class="ui teal selectable celled striped very compact small table" style="border-collapse:collapse;">
      <tbody>
      <% @priklady.each do |pr| %>
          <tr>
            <td class="two wide column" rowspan="3" style="border-bottom: 2pt solid black;">
              <span class="ui label">Príklad <%= pr.cislo_v_kole %></span>
            </td>
            <td>
              <h5>Text pred príkladom</h5>
              <br>
              <% if !pr.pred_t.blank? %>
                  <%= pr.pred_t %>
              <% else %>
                  Nezadaný.
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              <h5>Text príkladu</h5>
              <br>
              <% if !pr.text.blank? %>
                  <%= pr.text %>
              <% else %>
                  Nezadaný.
              <% end %>
            </td>
          </tr>
          <tr>
            <td style="border-bottom: 2pt solid black;">
              <h5>Text po príklade</h5>
              <br>
              <% if !pr.po_t.blank? %>
                  <%= pr.po_t %>
              <% else %>
                  Nezadaný.
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="ui yellow icon message">
      <i class="info icon"></i>
      <div class="content">
        <div class="header">
          Zadania neobsahujú žiadny príklad.
        </div>
        <p>Skús najprv nejaký pridať
          v <%= link_to "kole", kolo_path(Kolo.where(rocnik: @knizka.rocnik, seria: @knizka.seria, cislo: @c_kolo).take) %>
          .</p>
      </div>
    </div>
<% end %>

app/views/knizkas/zadania_edit.html.erb
<div class="ui fluid segment">
  <div class="ui breadcrumb">
    <%= link_to "Home", homepages_path, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <%= link_to "#{@knizka.rocnik}. ročník", rocnik_path(Rocnik.find_by_cislo(@knizka.rocnik)), class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="section"><%= @knizka.seria %> séria</div>
    <i class="right chevron icon divider"></i>
    <%= link_to "#{@knizka.cislo}. knižka", @knizka, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <%= link_to "Zadania", zadania_knizka_path(@knizka, @obsah.id), class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="active section">Úprava zadaní</div>
  </div>
</div>

<div class="ui grid">
  <div class="fourteen wide column"><h1>Úprava zadaní <%= @c_kolo %>. kola</h1>
  </div>
  <div class="column">
    <h1>
      <%= link_to zadania_knizka_path(@knizka, @obsah.id) do %>
          <i class="ui large right aligned arrow circle outline left link icon"></i>
      <% end %>
    </h1>
  </div>
</div>

<% if @priklady.any? %>
    <%= form_tag zadania_edit_knizka_path(@knizka, @obsah.id), class: 'ui form' do %>
        <table class="ui teal selectable celled striped very compact small table" style="border-collapse:collapse;">
          <tbody>
          <% @priklady.each do |pr| %>
              <tr>
                <td class="two wide column" rowspan="3" style="border-bottom: 2pt solid black;">
                  <span class="ui label">Príklad <%= pr.cislo_v_kole %></span>
                </td>
                <td>
                  <h5>Text pred príkladom</h5>
                  <br>
                  <%= text_area_tag "pred_t_#{pr.cislo_v_kole}", pr.pred_t %>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Text príkladu</h5>
                  <br>
                  <%= text_area_tag "text_#{pr.cislo_v_kole}", pr.text %>
                </td>
              </tr>
              <tr>
                <td style="border-bottom: 2pt solid black;">
                  <h5>Text po príklade</h5>
                  <br>
                  <%= text_area_tag "po_t_#{pr.cislo_v_kole}", pr.po_t %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= submit_tag "Uložiť", class: 'ui green button' %>
    <% end %>
<% else %>
    <div class="ui yellow icon message">
      <i class="info icon"></i>
      <div class="content">
        <div class="header">
          Zadania neobsahujú žiadny príklad.
        </div>
        <p>Skús najprv nejaký pridať
          v <%= link_to "kole", kolo_path(Kolo.where(rocnik: @knizka.rocnik, seria: @knizka.seria, cislo: @c_kolo).take) %>
          .</p>
      </div>
    </div>
<% end %>