config/routes.rb
Rails.application.routes.draw do

  resources :opravas

  resources :organizators

  resources :riesitel_seria do
    collection do
      get :riesitelia_serie
      post :edit_riesitels
    end
  end

  resources :riesitels do
    collection do
      post :add_riesitels
      post :add_riesitels_to_seria
    end
  end

  resources :homepages do
    collection do
      get :login
      post :login
    end
  end

  root "homepages#login"

  resources :komentars

  resources :priklads do
    member do
      get :edit_priklad
      patch :edit_priklad
    end
  end

  resources :kolos do
    member do
      post :add_priklads
      delete :remove_priklad
    end
  end

  resources :knizkas do
    member do
      post :add_obsah
      delete :remove_obsah
      get :zadania
      get :zadania_edit
      post :zadania_edit
      patch :zadania_edit
      get :vzoraky
      get :vysledkovka
      get :clanok
      post :gen_pdf
    end
  end

  resources :seria do
    resources :knizkas
  end

  resources :rocniks

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/knizka.rb
class Knizka < ActiveRecord::Base
  has_many :knizka_obsahs, dependent: :destroy
  has_many :pdfs, dependent: :destroy
end

app/models/knizka_obsah.rb
class KnizkaObsah < ActiveRecord::Base
  belongs_to :knizka
end

app/models/kolo.rb
class Kolo < ActiveRecord::Base
  has_many :priklads
end

app/models/komentar.rb
class Komentar < ActiveRecord::Base
  belongs_to :priklad
end

app/models/oprava.rb
class Oprava < ActiveRecord::Base
end

app/models/organizator.rb
class Organizator < ActiveRecord::Base
end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  belongs_to :knizka
end

app/models/priklad.rb
class Priklad < ActiveRecord::Base
  has_many :komentars, dependent: :destroy
  belongs_to :kolo
end

app/models/riesitel.rb
class Riesitel < ActiveRecord::Base
  has_many :riesitel_seria
end

app/models/riesitel_serium.rb
class RiesitelSerium < ActiveRecord::Base
  belongs_to :riesitel
  belongs_to :serium
end

app/models/rocnik.rb
class Rocnik < ActiveRecord::Base
  after_save :create_serie_kola

  def name
    "#{cislo}. ročník"
  end

  def create_serie_kola
    z = Serium.create(nazov: 'Zimná', rocnik: cislo)
    l = Serium.create(nazov: 'Letná', rocnik: cislo)
    (1..3).each do |c|
      Kolo.create(cislo: c, seria: 'Zimná', rocnik: cislo)
      Kolo.create(cislo: c, seria: 'Letná', rocnik: cislo)
    end
  end
end

app/models/serium.rb
class Serium < ActiveRecord::Base
  has_many :riesitel_seria
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, only: [:show, :edit, :update, :destroy]
  layout 'login', :only => [:login]

  # GET /homepages
  # GET /homepages.json
  def index
    @homepages = Homepage.all
    @aktualny_rocnik = Rocnik.all.order('cislo DESC').first
    @aktualna_knizka = Knizka.where(rocnik: @aktualny_rocnik.cislo).order('seria ASC').order('cislo DESC').first
    @kola_l = Kolo.where(rocnik: @aktualny_rocnik.cislo, seria: 'Letná').order(:cislo)
    @knizky_l = Knizka.where(rocnik: @aktualny_rocnik.cislo, seria: 'Letná').order(:cislo)
    @seria_l = Serium.where(rocnik: @aktualny_rocnik.cislo, nazov: 'Letná').take
  end

  def login
    if !params[:commit].blank? && params[:notice] == 'login' && params[:username] == 'user' && params[:pass] == 'user'
      redirect_to homepages_path
    end
  end

  # GET /homepages/1
  # GET /homepages/1.json
  def show
  end

  # GET /homepages/new
  def new
    @homepage = Homepage.new
  end

  # GET /homepages/1/edit
  def edit
  end

  # POST /homepages
  # POST /homepages.json
  def create
    @homepage = Homepage.new(homepage_params)

    respond_to do |format|
      if @homepage.save
        format.html { redirect_to @homepage, notice: 'Homepage was successfully created.' }
        format.json { render :show, status: :created, location: @homepage }
      else
        format.html { render :new }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homepages/1
  # PATCH/PUT /homepages/1.json
  def update
    respond_to do |format|
      if @homepage.update(homepage_params)
        format.html { redirect_to @homepage, notice: 'Homepage was successfully updated.' }
        format.json { render :show, status: :ok, location: @homepage }
      else
        format.html { render :edit }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepages/1
  # DELETE /homepages/1.json
  def destroy
    @homepage.destroy
    respond_to do |format|
      format.html { redirect_to homepages_url, notice: 'Homepage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homepage_params
      params.fetch(:homepage, {})
    end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/knizkas_helper.rb
module KnizkasHelper
end

app/helpers/kolos_helper.rb
module KolosHelper
end

app/helpers/komentars_helper.rb
module KomentarsHelper
end

app/helpers/opravas_helper.rb
module OpravasHelper
end

app/helpers/priklads_helper.rb
module PrikladsHelper
end

app/helpers/riesitels_helper.rb
module RiesitelsHelper
end

app/helpers/rocniks_helper.rb
module RocniksHelper
end

app/helpers/seria_helper.rb
module SeriaHelper
end

app/views/homepages/_form.html.erb
<%= form_for(@homepage) do |f| %>
  <% if @homepage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homepage.errors.count, "error") %> prohibited this homepage from being saved:</h2>

      <ul>
      <% @homepage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homepages/edit.html.erb
<h1>Editing Homepage</h1>

<%= render 'form' %>

<%= link_to 'Show', @homepage %> |
<%= link_to 'Back', homepages_path %>

app/views/homepages/index.html.erb
<h1>Aktuálne</h1>

<div class="ui three cards">
  <% if !@aktualna_knizka.blank? %>
      <div class="card">
        <div class="content">
          <div class="header">
            <%= link_to knizka_path(@aktualna_knizka) do %>
                Knižka
                <i class="blue unhide icon"></i>
            <% end %>
          </div>
          <div class="meta">
            <%= @aktualna_knizka.rocnik %>.
            ročník, <%= @aktualna_knizka.seria %> séria,
            <%= @aktualna_knizka.cislo %>. knižka
          </div>
          <div class="description m-t-1">
            <% if @aktualna_knizka.knizka_obsahs.count > 0 %>
                <div class="ui list">
                  <% @aktualna_knizka.knizka_obsahs.order(:cislo).each do |k| %>
                      <div class="item">
                        <% if k.nazov.start_with?('Zadania') %>
                            <%= link_to zadania_knizka_path(@aktualna_knizka, k.id), class: 'link-border' do %>
                                <%= k.nazov %>
                                <i class="blue unhide link icon"></i>
                            <% end %>
                        <% elsif k.nazov.start_with?('Vzoráky') %>
                            <%= link_to nil, data: { confirm: 'Not implemented.' }, class: 'link-border' do %>
                                <%= k.nazov %>
                                <i class="blue unhide link icon"></i>
                            <% end %>
                        <% elsif k.nazov.start_with?('Výsledkovka') %>
                            <%= link_to nil, data: { confirm: 'Not implemented.' }, class: 'link-border' do %>
                                <%= k.nazov %>
                                <i class="blue unhide link icon"></i>
                            <% end %>
                        <% elsif k.nazov.start_with?('Článok') %>
                            <%= link_to nil, data: { confirm: 'Not implemented.' }, class: 'link-border' do %>
                                <%= k.nazov %>
                                <i class="blue unhide link icon"></i>
                            <% end %>
                            <%= link_to nil, data: { confirm: 'Not implemented.' }, class: 'link-border' do %>
                                <%= k.nazov %>
                                <i class="yellow edit link icon"></i>
                            <% end %>
                        <% end %>
                      </div>
                  <% end %>
                </div>
            <% else %>
                Knižka zatiaľ nemá obsah.
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
  <div class="card">
    <div class="content">
      <div class="header">
        <%= link_to rocnik_path(@aktualny_rocnik) do %>
            Ročník, séria
            <i class="blue unhide link icon"></i>
        <% end %>
      </div>
      <div class="meta">
        <%= @aktualny_rocnik.cislo %>. ročník, Letná séria
      </div>
    </div>
    <div class="content">
      <div class="header">Knižky</div>
      <div class="ui list">
        <% @knizky_l.each do |k| %>
            <div class="item">
              <%= link_to k, class: 'link-border' do %>
                  <%= "#{k.cislo}. knižka" %>
                  <i class="blue unhide link icon"></i>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="content">
      <div class="header">Kolá</div>
      <div class="ui list">
        <% @kola_l.each do |kolo| %>
            <div class="item">
              <%= link_to kolo, class: 'link-border' do %>
                  <%= "#{kolo.cislo}. kolo" %>
                  <i class="blue unhide link icon"></i>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="content">
      <div class="header">Riešitelia</div>
      <%= link_to riesitels_path(seria_id: @seria_l.id), class: 'link-border' do %>
          Pridať riešiteľov
          <i class="green plus circle link icon"></i>
      <% end %>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">
        Opravovanie
      </div>
      <div class="meta">
        <%= @aktualny_rocnik.cislo %>.
        ročník, Letná séria,
        1. kolo
      </div>
      <div class="description m-t-1">
        <div class="ui fluid vertical inverted buttons">
          <%= link_to "Prihlás sa", opravas_path(rocnik: @aktualny_rocnik.cislo, seria: 'Letná', kolo: 1), class: 'ui green button' %>
          <% o = Oprava.where(rocnik: @aktualny_rocnik.cislo, seria: 'Letná', kolo: 1).take %>
          <% if o && !o.priklady.blank? && !eval(o.priklady).blank? %>
              <%= link_to "Zadaj body", nil, data: { confirm: 'Not implemented.' }, class: 'ui button' %>
              <%= link_to "Napíš vzorák", edit_oprava_path(o, rocnik: @aktualny_rocnik.cislo, seria: 'Letná', kolo: 1), class: 'ui green button' %>
          <% else %>
              <%= link_to "Zadaj body", nil, data: { confirm: 'Nie si prihlásený na žiadne opravovanie.' }, class: 'ui button' %>
              <%= link_to "Napíš vzorák", nil, data: { confirm: 'Nie si prihlásený na žiadne opravovanie.' }, class: 'ui button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<h1>Štatistiky</h1>

<div class="ui three cards">
  <div class="card">
    <div class="content">
      <div class="header">
        Knižka
      </div>
      <div class="meta">
        Počet vykonaných zmien
      </div>
      <div class="description">
        <div class="ui celled ordered list">
          <div class="item">
            <span class="ui teal circular right floated label">25</span>
            Jakub
          </div>
          <div class="item">
            <span class="ui teal circular right floated label">12</span>
            Barbora
          </div>
          <div class="item">
            <span class="ui teal circular right floated label">7</span>
            Marianna
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">
        Príklady
      </div>
      <div class="meta">
        Počet pridaných príkladov
      </div>
      <div class="description">
        <div class="ui celled ordered list">
          <div class="item">
            <span class="ui teal circular right floated label">52</span>
            Jakub
          </div>
          <div class="item">
            <span class="ui teal circular right floated label">28</span>
            Barbora
          </div>
          <div class="item">
            <span class="ui teal circular right floated label">21</span>
            Marianna
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">
        Opravovanie
      </div>
      <div class="meta">
        Počet opravených príkladov
      </div>
      <div class="description">
        <div class="ui celled ordered list">
          <div class="item">
            <span class="ui teal circular right floated label">8</span>
            Jakub
          </div>
          <div class="item">
            <span class="ui teal circular right floated label">5</span>
            Barbora
          </div>
          <div class="item">
            <span class="ui teal circular right floated label">3</span>
            Marianna
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<h1>Aktivity</h1>

<table class="ui teal selectable celled striped table">
  <thead>
  <tr>
    <th>Aktivita</th>
    <th>Čas</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Barbora zmenila
      príklad <%= link_to Priklad.first.try(:nazov), Priklad.first %></td>
    <td>26.10.2016 21:15</td>
  </tr>
  <% if !@aktualna_knizka.blank? %>
      <tr>
        <td>Jakub
          zmenil <%= link_to "knižku #{@aktualna_knizka.cislo}", @aktualna_knizka %></td>
        <td>26.10.2016 17:45</td>
      </tr>
  <% end %>
  <tr>
    <td>Marianna pridala
      body <%= link_to "opravovania", nil, data: { confirm: 'Not implemented.' } %></td>
    <td>25.10.2016 13:15</td>
  </tr>
  </tbody>
</table>

app/views/homepages/new.html.erb
<h1>New Homepage</h1>

<%= render 'form' %>

<%= link_to 'Back', homepages_path %>

app/views/homepages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_homepage_path(@homepage) %> |
<%= link_to 'Back', homepages_path %>