config/routes.rb
Rails.application.routes.draw do

  resources :opravas

  resources :organizators

  resources :riesitel_seria do
    collection do
      get :riesitelia_serie
      post :edit_riesitels
    end
  end

  resources :riesitels do
    collection do
      post :add_riesitels
      post :add_riesitels_to_seria
    end
  end

  resources :homepages do
    collection do
      get :login
      post :login
    end
  end

  root "homepages#login"

  resources :komentars

  resources :priklads do
    member do
      get :edit_priklad
      patch :edit_priklad
    end
  end

  resources :kolos do
    member do
      post :add_priklads
      delete :remove_priklad
    end
  end

  resources :knizkas do
    member do
      post :add_obsah
      delete :remove_obsah
      get :zadania
      get :zadania_edit
      post :zadania_edit
      patch :zadania_edit
      get :vzoraky
      get :vysledkovka
      get :clanok
      post :gen_pdf
    end
  end

  resources :seria do
    resources :knizkas
  end

  resources :rocniks

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/knizka.rb
class Knizka < ActiveRecord::Base
  has_many :knizka_obsahs, dependent: :destroy
  has_many :pdfs, dependent: :destroy
end

app/models/knizka_obsah.rb
class KnizkaObsah < ActiveRecord::Base
  belongs_to :knizka
end

app/models/kolo.rb
class Kolo < ActiveRecord::Base
  has_many :priklads
end

app/models/komentar.rb
class Komentar < ActiveRecord::Base
  belongs_to :priklad
end

app/models/oprava.rb
class Oprava < ActiveRecord::Base
end

app/models/organizator.rb
class Organizator < ActiveRecord::Base
end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  belongs_to :knizka
end

app/models/priklad.rb
class Priklad < ActiveRecord::Base
  has_many :komentars, dependent: :destroy
  belongs_to :kolo
end

app/models/riesitel.rb
class Riesitel < ActiveRecord::Base
  has_many :riesitel_seria
end

app/models/riesitel_serium.rb
class RiesitelSerium < ActiveRecord::Base
  belongs_to :riesitel
  belongs_to :serium
end

app/models/rocnik.rb
class Rocnik < ActiveRecord::Base
  after_save :create_serie_kola

  def name
    "#{cislo}. ročník"
  end

  def create_serie_kola
    z = Serium.create(nazov: 'Zimná', rocnik: cislo)
    l = Serium.create(nazov: 'Letná', rocnik: cislo)
    (1..3).each do |c|
      Kolo.create(cislo: c, seria: 'Zimná', rocnik: cislo)
      Kolo.create(cislo: c, seria: 'Letná', rocnik: cislo)
    end
  end
end

app/models/serium.rb
class Serium < ActiveRecord::Base
  has_many :riesitel_seria
end

app/controllers/kolos_controller.rb
class KolosController < ApplicationController
  before_action :set_kolo, only: [:show, :edit, :update, :destroy, :add_priklads, :remove_priklad]

  # GET /kolos
  # GET /kolos.json
  def index
    @kolos = Kolo.all
  end

  # GET /kolos/1
  # GET /kolos/1.json
  def show
    @priklads = Priklad.where(kolo_id: nil)
    @knizka = Knizka.where(rocnik: @kolo.rocnik, seria: @kolo.seria).take
    if @knizka
      @zadania = @knizka.knizka_obsahs.where(nazov: "Zadania #{@kolo.cislo}. kola").take
    end
  end

  def add_priklads
    pr_cnt = @kolo.priklads.count

    unless params[:priklads].blank?
      if params[:priklads].size + pr_cnt > 10
        redirect_to :back, notice: 'too_many_priklads'
      else
        params[:priklads].each do |p|
          priklad = Priklad.find(p)
          new_cislo = 0
          (1..10).each do |c|
            unless @kolo.priklads.where(cislo_v_kole: c).take
              new_cislo = c
              break
            end
          end
          if new_cislo != 0
            priklad.update(kolo: @kolo, cislo_v_kole: new_cislo)
          end
        end

        redirect_to :back, notice: 'ok'
      end
    else
      redirect_to :back, notice: 'no_priklads'
    end
  end

  def remove_priklad
    ps = @kolo.priklads.where(cislo_v_kole: params[:format])
    ps.each do |p|
      p.update(kolo: nil, cislo_v_kole: nil)
    end
    redirect_to :back, notice: 'deleted'
  end

  # GET /kolos/new
  def new
    @kolo = Kolo.new
  end

  # GET /kolos/1/edit
  def edit
  end

  # POST /kolos
  # POST /kolos.json
  def create
    @kolo = Kolo.new(kolo_params)

    respond_to do |format|
      if @kolo.save
        format.html { redirect_to @kolo, notice: 'Kolo was successfully created.' }
        format.json { render :show, status: :created, location: @kolo }
      else
        format.html { render :new }
        format.json { render json: @kolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kolos/1
  # PATCH/PUT /kolos/1.json
  def update
    respond_to do |format|
      if @kolo.update(kolo_params)
        format.html { redirect_to @kolo, notice: 'Kolo was successfully updated.' }
        format.json { render :show, status: :ok, location: @kolo }
      else
        format.html { render :edit }
        format.json { render json: @kolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kolos/1
  # DELETE /kolos/1.json
  def destroy
    @kolo.destroy
    respond_to do |format|
      format.html { redirect_to kolos_url, notice: 'Kolo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_kolo
    @kolo = Kolo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kolo_params
    params.require(:kolo).permit(:cislo, :rocnik, :seria)
  end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/knizkas_helper.rb
module KnizkasHelper
end

app/helpers/kolos_helper.rb
module KolosHelper
end

app/helpers/komentars_helper.rb
module KomentarsHelper
end

app/helpers/opravas_helper.rb
module OpravasHelper
end

app/helpers/priklads_helper.rb
module PrikladsHelper
end

app/helpers/riesitels_helper.rb
module RiesitelsHelper
end

app/helpers/rocniks_helper.rb
module RocniksHelper
end

app/helpers/seria_helper.rb
module SeriaHelper
end

app/views/kolos/_form.html.erb
<%= form_for(@kolo) do |f| %>
  <% if @kolo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kolo.errors.count, "error") %> prohibited this kolo from being saved:</h2>

      <ul>
      <% @kolo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cislo %><br>
    <%= f.number_field :cislo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kolos/edit.html.erb
<h1>Editing Kolo</h1>

<%= render 'form' %>

<%= link_to 'Show', @kolo %> |
<%= link_to 'Back', kolos_path %>

app/views/kolos/index.html.erb
  <p id="notice"><%= notice %></p>

<h1>Listing Kolos</h1>

<table>
  <thead>
    <tr>
      <th>Cislo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kolos.each do |kolo| %>
      <tr>
        <td><%= kolo.cislo %></td>
        <td><%= link_to 'Show', kolo %></td>
        <td><%= link_to 'Edit', edit_kolo_path(kolo) %></td>
        <td><%= link_to 'Destroy', kolo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kolo', new_kolo_path %>

app/views/kolos/new.html.erb
<h1>New Kolo</h1>

<%= render 'form' %>

<%= link_to 'Back', kolos_path %>

app/views/kolos/show.html.erb
<div class="ui fluid segment">
  <div class="ui breadcrumb">
    <%= link_to "Home", homepages_path, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <%= link_to "#{@kolo.rocnik}. ročník", rocnik_path(Rocnik.find_by_cislo(@kolo.rocnik)), class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="section"><%= @kolo.seria %> séria</div>
    <i class="right chevron icon divider"></i>
    <div class="active section"><%= @kolo.cislo %>. kolo</div>
  </div>
</div>

<% if notice == 'ok' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Príklady boli úspešne pridané do zadaní.
        </div>
        <p>Teraz môžeš upraviť ich poradie.</p>
      </div>
    </div>
<% elsif notice == 'too_many_priklads' %>
    <div class="ui red icon message">
      <i class="meh icon"></i>
      <div class="content">
        <div class="header">
          Nastala chyba pri pridávaní príkladov do zadaní.
        </div>
        <p>V zadaniach by po pridaní bolo viac ako 10 príkladov.</p>
      </div>
    </div>
<% elsif notice == 'deleted' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Príklad bol úspešne odobraný.
        </div>
        <p>Teraz môžeš pridať ďalší príklad do zadaní.</p>
      </div>
    </div>
<% elsif notice == 'no_priklads' %>
    <div class="ui red icon message">
      <i class="meh icon"></i>
      <div class="content">
        <div class="header">
          Nastala chyba pri pridávaní príkladov do zadaní.
        </div>
        <p>Nevybral si žiadny príklad.</p>
      </div>
    </div>
<% end %>

<h1><%= @kolo.cislo %>. kolo</h1>
<h2>Príklady v kole</h2>

<div class="ui two column grid">
  <div class="column">
    <h3>Vybrané príklady</h3>
    <table class="ui teal selectable celled striped very compact small table">
      <thead>
      <tr>
        <th class="one wide"></th>
        <th class="one wide">č.</th>
        <th class="eight wide">Názov</th>
        <th class="six wide">Akcie</th>
      </tr>
      </thead>

      <tbody>
      <% (1..10).each do |c| %>
          <% p = @kolo.priklads.where(cislo_v_kole: c).take %>
          <% if p %>
              <tr>
                <td>
                  <% if c != 1 %>
                      <i class="caret up link icon move_up" id="up<%= c %>"></i>
                  <% end %>
                  <% if c != 10 %>
                      <i class="caret down link icon move_down" id="down<%= c %>"></i>
                  <% end %>
                </td>
                <td><%= c %></td>
                <td id="prikladN<%= c %>"><%= p.nazov %></td>
                <td id="prikladA<%= c %>">
                  <div class="ui basic buttons">
                    <%= link_to p, class: 'ui button' do %>
                        <i class="blue unhide link icon"></i>
                    <% end %>
                    <%= link_to edit_priklad_path(p), class: 'ui button' do %>
                        <i class="yellow edit link icon"></i>
                    <% end %>
                    <%= link_to remove_priklad_kolo_path(@kolo, c), class: 'ui button', method: :delete, data: { confirm: 'Naozaj chceš odobrať tento príklad zo zadaní?' } do %>
                        <i class="red remove link icon"></i>
                    <% end %>
                  </div>
                </td>
              </tr>
          <% else %>
              <tr>
                <td></td>
                <td><%= c %></td>
                <td></td>
                <td></td>
              </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="column">
    <h3>Výber z príkladov</h3>
    <%= form_tag url_for(:controller => 'kolos', :action => 'add_priklads'), class: 'ui form' do %>
        <div id="filter-priklad"></div>
        <table id="vyber-priklad" class="ui teal selectable celled striped very compact small table dataTable">
          <thead>
          <tr>
            <th class="one wide"></th>
            <th class="four wide">Názov</th>
            <th class="three wide">Autor</th>
            <th class="two wide">Kategória</th>
            <th class="two wide">Stav</th>
            <th class="four wide">Akcie</th>
          </tr>
          </thead>

          <tbody>
          <% @priklads.each do |priklad| %>
              <tr>
                <td><%= check_box_tag "priklads[]", priklad.id %></td>
                <td><%= priklad.nazov %></td>
                <td><%= priklad.autor %></td>
                <td><%= priklad.kategoria %></td>
                <td><%= priklad.stav %></td>
                <td>
                  <%= link_to priklad do %>
                      <i class="blue unhide link icon"></i>
                  <% end %>
                  <%= link_to edit_priklad_path(priklad) do %>
                      <i class="yellow edit link icon"></i>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= submit_tag "Vyber príklady", class: 'ui green button' %>
    <% end %>
  </div>
</div>

<h2>Texty v zadaniach</h2>
<div class="ui">
  <% if @knizka && @zadania %>
      <%= link_to "Zobraziť zadania", zadania_knizka_path(@knizka, @zadania.id), class: 'ui green button' %>
  <% else %>
      <div class="ui yellow icon message">
        <i class="info icon"></i>
        <div class="content">
          <div class="header">
            Zadania tohoto kola nie sú v knižke.
          </div>
          <p>Aby bolo možné zobraziť texty, musíš najprv priradiť zadania do
             <%= link_to "knižky", rocnik_path(Rocnik.find_by_cislo(@kolo.rocnik)), style: 'color: #B58105; text-decoration: underline;' %>.</p>
        </div>
      </div>
  <% end %>
</div>