config/routes.rb
Rails.application.routes.draw do

  resources :opravas

  resources :organizators

  resources :riesitel_seria do
    collection do
      get :riesitelia_serie
      post :edit_riesitels
    end
  end

  resources :riesitels do
    collection do
      post :add_riesitels
      post :add_riesitels_to_seria
    end
  end

  resources :homepages do
    collection do
      get :login
      post :login
    end
  end

  root "homepages#login"

  resources :komentars

  resources :priklads do
    member do
      get :edit_priklad
      patch :edit_priklad
    end
  end

  resources :kolos do
    member do
      post :add_priklads
      delete :remove_priklad
    end
  end

  resources :knizkas do
    member do
      post :add_obsah
      delete :remove_obsah
      get :zadania
      get :zadania_edit
      post :zadania_edit
      patch :zadania_edit
      get :vzoraky
      get :vysledkovka
      get :clanok
      post :gen_pdf
    end
  end

  resources :seria do
    resources :knizkas
  end

  resources :rocniks

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/knizka.rb
class Knizka < ActiveRecord::Base
  has_many :knizka_obsahs, dependent: :destroy
  has_many :pdfs, dependent: :destroy
end

app/models/knizka_obsah.rb
class KnizkaObsah < ActiveRecord::Base
  belongs_to :knizka
end

app/models/kolo.rb
class Kolo < ActiveRecord::Base
  has_many :priklads
end

app/models/komentar.rb
class Komentar < ActiveRecord::Base
  belongs_to :priklad
end

app/models/oprava.rb
class Oprava < ActiveRecord::Base
end

app/models/organizator.rb
class Organizator < ActiveRecord::Base
end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  belongs_to :knizka
end

app/models/priklad.rb
class Priklad < ActiveRecord::Base
  has_many :komentars, dependent: :destroy
  belongs_to :kolo
end

app/models/riesitel.rb
class Riesitel < ActiveRecord::Base
  has_many :riesitel_seria
end

app/models/riesitel_serium.rb
class RiesitelSerium < ActiveRecord::Base
  belongs_to :riesitel
  belongs_to :serium
end

app/models/rocnik.rb
class Rocnik < ActiveRecord::Base
  after_save :create_serie_kola

  def name
    "#{cislo}. ročník"
  end

  def create_serie_kola
    z = Serium.create(nazov: 'Zimná', rocnik: cislo)
    l = Serium.create(nazov: 'Letná', rocnik: cislo)
    (1..3).each do |c|
      Kolo.create(cislo: c, seria: 'Zimná', rocnik: cislo)
      Kolo.create(cislo: c, seria: 'Letná', rocnik: cislo)
    end
  end
end

app/models/serium.rb
class Serium < ActiveRecord::Base
  has_many :riesitel_seria
end

app/controllers/rocniks_controller.rb
class RocniksController < ApplicationController
  before_action :set_rocnik, only: [:show, :edit, :update, :destroy]

  # GET /rocniks
  # GET /rocniks.json
  def index
    @rocniks = Rocnik.all
  end

  # GET /rocniks/1
  # GET /rocniks/1.json
  def show
    @kola_z = Kolo.where(rocnik: @rocnik.cislo, seria: 'Zimná').order(:cislo)
    @kola_l = Kolo.where(rocnik: @rocnik.cislo, seria: 'Letná').order(:cislo)
    @seria_z = Serium.where(rocnik: @rocnik.cislo, nazov: 'Zimná').take
    @seria_l = Serium.where(rocnik: @rocnik.cislo, nazov: 'Letná').take
    @knizky_z = Knizka.where(rocnik: @rocnik.cislo, seria: 'Zimná').order(:cislo)
    @knizky_l = Knizka.where(rocnik: @rocnik.cislo, seria: 'Letná').order(:cislo)
  end

  # GET /rocniks/new
  def new
    max = Rocnik.order('cislo DESC').first
    redirect_to Rocnik.create(cislo: max.cislo + 1), notice: 'rocnik_added'
  end

  # GET /rocniks/1/edit
  def edit
  end

  # POST /rocniks
  # POST /rocniks.json
  def create
    @rocnik = Rocnik.new(rocnik_params)

    respond_to do |format|
      if @rocnik.save
        format.html { redirect_to @rocnik, notice: 'Rocnik was successfully created.' }
        format.json { render :show, status: :created, location: @rocnik }
      else
        format.html { render :new }
        format.json { render json: @rocnik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rocniks/1
  # PATCH/PUT /rocniks/1.json
  def update
    respond_to do |format|
      if @rocnik.update(rocnik_params)
        format.html { redirect_to @rocnik, notice: 'Rocnik was successfully updated.' }
        format.json { render :show, status: :ok, location: @rocnik }
      else
        format.html { render :edit }
        format.json { render json: @rocnik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rocniks/1
  # DELETE /rocniks/1.json
  def destroy
    @rocnik.destroy
    respond_to do |format|
      format.html { redirect_to rocniks_url, notice: 'Rocnik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_rocnik
    @rocnik = Rocnik.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rocnik_params
    params.require(:rocnik).permit(:cislo)
  end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/knizkas_helper.rb
module KnizkasHelper
end

app/helpers/kolos_helper.rb
module KolosHelper
end

app/helpers/komentars_helper.rb
module KomentarsHelper
end

app/helpers/opravas_helper.rb
module OpravasHelper
end

app/helpers/priklads_helper.rb
module PrikladsHelper
end

app/helpers/riesitels_helper.rb
module RiesitelsHelper
end

app/helpers/rocniks_helper.rb
module RocniksHelper
end

app/helpers/seria_helper.rb
module SeriaHelper
end

app/views/rocniks/_form.html.erb
<%= form_for(@rocnik) do |f| %>
  <% if @rocnik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rocnik.errors.count, "error") %> prohibited this rocnik from being saved:</h2>

      <ul>
      <% @rocnik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cislo %><br>
    <%= f.number_field :cislo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rocniks/edit.html.erb
<h1>Editing Rocnik</h1>

<%= render 'form' %>

<%= link_to 'Show', @rocnik %> |
<%= link_to 'Back', rocniks_path %>

app/views/rocniks/index.html.erb
<div class="ui fluid segment">
  <div class="ui breadcrumb">
    <%= link_to "Home", homepages_path, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="active section">Ročníky</div>
  </div>
</div>

<span id="notice"><%= notice %></span>

<h1>19. ročník, 2016/2017</h1>

<table>
  <thead>
    <tr>
      <th>Cislo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rocniks.each do |rocnik| %>
      <tr>
        <td><%= rocnik.cislo %></td>
        <td><%= link_to 'Show', rocnik %></td>
        <td><%= link_to 'Edit', edit_rocnik_path(rocnik) %></td>
        <td><%= link_to 'Destroy', rocnik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rocnik', new_rocnik_path %>

app/views/rocniks/new.html.erb
<h1>New Rocnik</h1>

<%= render 'form' %>

<%= link_to 'Back', rocniks_path %>

app/views/rocniks/show.html.erb
<div class="ui fluid segment">
  <div class="ui breadcrumb">
    <%= link_to "Home", homepages_path, class: 'section' %>
    <i class="right chevron icon divider"></i>
    <div class="active section"><%= @rocnik.cislo %>. ročník</div>
  </div>
</div>

<% if notice == 'knizka_added' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Knižka bola úspešne pridaná.
        </div>
        <p>Teraz si ju môžeš prezerať a upravovať.</p>
      </div>
    </div>
<% elsif notice == 'rocnik_added' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Ročník bol úspešne pridaný.
        </div>
        <p>Teraz si ho môžeš prezerať a upravovať jeho obsah.</p>
      </div>
    </div>
<% elsif notice == 'knizka_deleted' %>
    <div class="ui green icon message">
      <i class="check mark icon"></i>
      <div class="content">
        <div class="header">
          Knižka bola úspešne odobraná.
        </div>
      </div>
    </div>

<% end %>

<div class="ui grid">
  <div class="eight wide column">
    <h1><%= @rocnik.cislo %>. ročník, <%= @rocnik.cislo + 1997 %>
      /<%= @rocnik.cislo + 1998 %></h1>
  </div>
  <div class="eight wide right aligned column">

    <h2>
      <select onChange="if(this.selectedIndex!=0) self.location=this.options[this.selectedIndex].value" class="field">
        <option value="/rocniks/<%= @rocnik.id %>">Zmeniť ročník</option>
        <% Rocnik.order('cislo DESC').each do |r| %>
            <option value="/rocniks/<%= r.id %>"><%= r.name %></option>
        <% end %>
      </select>
      <%= link_to new_rocnik_path, data: { confirm: 'Naozaj chceš pridať ročník?' } do %>
          <i class="ui big right aligned green plus circle link icon"></i>
      <% end %>
    </h2>
  </div>
</div>

<div class="ui two column grid">
  <div class="column">
    <h2>Zimná séria</h2>
    <h3>Knižky<%= link_to new_serium_knizka_path(@seria_z), data: { confirm: 'Naozaj chceš pridať knižku do zimnej série?' } do %>
          <i class="ui right aligned green plus circle link icon"></i>
      <% end %>
    </h3>
    <div class="ui list">
      <% @knizky_z.each do |k| %>
          <div class="item">
            <span class="link-border">
                <%= link_to k do %>
                    <%= "#{k.cislo}. knižka" %>
                  <i class="blue unhide link icon"></i>
                <% end %>
              <%= link_to k, method: :delete, data: { confirm: "Naozaj chceš vymazať knižku #{k.cislo}. ?" } do %>
                    <i class="red remove link icon"></i>
                <% end %>
            </span>
          </div>
      <% end %>
    </div>

    <h3>Kolá</h3>
    <div class="ui list">
      <% @kola_z.each do |kolo| %>
          <div class="item">
            <%= link_to kolo, class: 'link-border' do %>
                <%= "#{kolo.cislo}. kolo" %>
                <i class="blue unhide link icon"></i>
            <% end %>
          </div>
      <% end %>
    </div>

    <h3>Riešitelia</h3>
    <%= link_to riesitelia_serie_riesitel_seria_path(id: @seria_z.id), class: 'link-border' do %>
        Pridaní riešitelia
        <i class="blue unhide link icon"></i>
    <% end %>
    <%= link_to riesitels_path(seria_id: @seria_z.id), class: 'link-border' do %>
        Pridať riešiteľov
        <i class="green plus circle link icon"></i>
    <% end %>
  </div>
  <div class="column">
    <h2>Letná séria</h2>
    <h3>Knižky<%= link_to new_serium_knizka_path(@seria_l), data: { confirm: 'Naozaj chceš pridať knižku do letnej série?' } do %>
          <i class="ui right aligned green plus circle link icon"></i>
      <% end %>
    </h3>
    <div class="ui list">
      <% @knizky_l.each do |k| %>
          <div class="item">
            <span class="link-border">
                <%= link_to k do %>
                    <%= "#{k.cislo}. knižka" %>
                  <i class="blue unhide link icon"></i>
                <% end %>
              <%= link_to k, method: :delete, data: { confirm: "Naozaj chceš vymazať knižku #{k.cislo}. ?" } do %>
                    <i class="red remove link icon"></i>
                <% end %>
            </span>
          </div>
      <% end %>
    </div>
    <h3>Kolá</h3>
    <div class="ui list">
      <% @kola_l.each do |kolo| %>
          <div class="item">
            <%= link_to kolo, class: 'link-border' do %>
                <%= "#{kolo.cislo}. kolo" %>
                <i class="blue unhide link icon"></i>
            <% end %>
          </div>
      <% end %>
    </div>
    <h3>Riešitelia</h3>
    <%= link_to riesitelia_serie_riesitel_seria_path(id: @seria_l.id), class: 'link-border' do %>
        Pridaní riešitelia
        <i class="blue unhide link icon"></i>
    <% end %>
    <%= link_to riesitels_path(seria_id: @seria_l.id), class: 'link-border' do %>
        Pridať riešiteľov
        <i class="green plus circle link icon"></i>
    <% end %>
  </div>
</div>